{
    "config": {
        "error": {
            "cannot_connect": "Nie mo\u017cna nawi\u0105za\u0107 po\u0142\u0105czenia",
            "invalid_auth": "Niepoprawne uwierzytelnienie",
            "no_appliances": "Nie znaleziono obs\u0142ugiwanych urz\u0105dze\u0144",
            "unknown": "Nieoczekiwany b\u0142\u0105d"
        },
        "step": {
            "user": {
                "data": {
                    "password": "Has\u0142o",
                    "username": "Nazwa u\u017cytkownika"
                }
            }
        }
    }
}