{
    "config": {
        "abort": {
            "already_configured": "O servi\u00e7o j\u00e1 est\u00e1 configurado",
            "reauth_successful": "A reautentica\u00e7\u00e3o foi bem-sucedida"
        },
        "error": {
            "cannot_connect": "Falha ao conectar",
            "invalid_auth": "Autentica\u00e7\u00e3o inv\u00e1lida"
        },
        "step": {
            "api_key": {
                "data": {
                    "api_key": "Chave da API"
                }
            },
            "reauth_confirm": {
                "data": {
                    "api_key": "Chave API"
                },
                "description": "Insira uma nova chave de API para o PI-Hole em {host}/{location}",
                "title": "Reautentica\u00e7\u00e3o da integra\u00e7\u00e3o do PI-Hole"
            },
            "user": {
                "data": {
                    "api_key": "Chave da API",
                    "host": "Nome do host",
                    "location": "Localiza\u00e7\u00e3o",
                    "name": "Nome",
                    "port": "Porta",
                    "ssl": "Usar um certificado SSL",
                    "statistics_only": "Somente estat\u00edsticas",
                    "verify_ssl": "Verifique o certificado SSL"
                }
            }
        }
    },
    "issues": {
        "deprecated_yaml": {
            "description": "A configura\u00e7\u00e3o do PI-Hole usando YAML est\u00e1 sendo removida. \n\n Sua configura\u00e7\u00e3o YAML existente foi importada para a IU automaticamente. \n\n Remova a configura\u00e7\u00e3o YAML do PI-Hole do arquivo configuration.yaml e reinicie o Home Assistant para corrigir esse problema.",
            "title": "A configura\u00e7\u00e3o YAML do PI-Hole est\u00e1 sendo removida"
        }
    }
}